---
name: Ethan's Profile

title: Ethan's Profile
description: Projects and more

remote_theme: pages-themes/cayman@v0.2.0
# theme: jekyll-theme-slate
plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
