---
name: Ethan's Profile

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
